---
- hosts: all
  become: true
  pre_tasks:
  
#    - name: POWEROFF
#      command: /sbin/shutdown -h now
  
    - name: install udpates (CentOS)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
    
    - name: install udpates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

    - name: install apached udpates (Ubuntu)
      tags: apache,apache2,ubuntu
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
