---
- hosts: all
  become: true
  pre_tasks:
  
#    - name: POWEROFF
#      command: /sbin/shutdown -h now
  
    - name: install udpates (CentOS)
      tags: always
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
    
    - name: install udpates (Ubuntu)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

    - name: install apache&PHP udpates (Ubuntu)
      tags: apache,apache2,ubuntu
      apt:
        name:
          - apache2
          - lib2apache2-mod-php
        state: latest
      when: ansible_distribution == "Ubuntu"

    - name: install apache&PHP udpates (CentOS)
      tags: apache,httpd,centos
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution == "CentOS"

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index1.html
        owner: root
        group: root
        mode: 0644