---
- hosts: all
  become: true
  pre_tasks:
  
#    - name: POWEROFF
#      command: /sbin/shutdown -h now
  
    - name: install udpates (CentOS)
      tags: centos
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"
    
    - name: install udpates (Ubuntu)
      tags: ubuntu
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Ubuntu"