---
- hosts: web_servers
  become: true
  tasks:

    - name: copy default html file for site
      tags: apache,apache2,httpd
      copy:
        src: default_site.html
        dest: /var/www/html/index1.html
        owner: root
        group: root
        mode: 0644

- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip
    
    - name: install terraform
      unarchive:
        src: https://release.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
        dest: /usr/local/bin
        remote_src:
        mode: 0755
        owner: root
                
        